id: A9CC31A1A
title: Brief Amitābha Sleeping Practice
type: translation
pechas:
- I47D9890D
- I153F9B13
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:05.462290
  last_modified_at: 2023-01-04 12:06:05.462294
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I47D9890D/5AAA: B8FF
  I153F9B13/0938: B8FF
